name = "gdm-nutrition-tracker"
compatibility_date = "2024-01-01"

[env.production]
name = "gdm-nutrition-tracker"

# 环境变量配置
[vars]
# 这里可以设置一些默认的环境变量

# 如果需要设置 ZHIPU_API_KEY，请在 Cloudflare Dashboard 中设置
# 或者在部署时通过命令行设置 